repos:
  - repo: local
    hooks:
      - id: alejandra
        name: alejandra (auto-format nix)
        entry: alejandra .
        language: system
        pass_filenames: false
        stages: [pre-commit]
